# SPDX-FileCopyrightText: 2025-present iilei • jochen preusche <922226+iilei@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- id: doc-inject
  name: Inject dynamic content into documentation
  entry: doc-inject run
  language: python
  files: \.(md|adoc|asciidoc|rst|html|jinja2|j2|yml|yaml|json5?)$
  pass_filenames: true
  # example args:
  # args: ["--config", "pyproject.toml", "--config-query", "tool.doc-inject"]
